// Major world container ports used for the demo watchlist.
// Coordinates are approximate harbor positions (decimal degrees).
import type { Port } from "./types";

export const PORTS: Port[] = [
  { name: "Port of Shanghai", country: "China", lat: 31.23, lon: 121.48 },
  { name: "Port of Singapore", country: "Singapore", lat: 1.26, lon: 103.82 },
  { name: "Ningbo-Zhoushan", country: "China", lat: 29.95, lon: 121.85 },
  { name: "Port of Shenzhen", country: "China", lat: 22.47, lon: 114.12 },
  { name: "Port of Guangzhou", country: "China", lat: 23.08, lon: 113.45 },
  { name: "Port of Busan", country: "South Korea", lat: 35.1, lon: 129.04 },
  { name: "Port of Qingdao", country: "China", lat: 36.05, lon: 120.32 },
  { name: "Port of Hong Kong", country: "China", lat: 22.3, lon: 114.17 },
  { name: "Port of Tianjin", country: "China", lat: 38.98, lon: 117.78 },
  { name: "Port of Rotterdam", country: "Netherlands", lat: 51.95, lon: 4.05 },
  { name: "Port of Antwerp", country: "Belgium", lat: 51.28, lon: 4.35 },
  { name: "Port of Los Angeles", country: "United States", lat: 33.73, lon: -118.26 },
  { name: "Port of New York and New Jersey", country: "United States", lat: 40.67, lon: -74.02 },
  { name: "Port of Savannah", country: "United States", lat: 32.08, lon: -81.1 },
  { name: "Port of Houston", country: "United States", lat: 29.72, lon: -95.08 },
  { name: "Port of Miami", country: "United States", lat: 25.77, lon: -80.17 },
  { name: "Port of New Orleans", country: "United States", lat: 29.95, lon: -90.05 },
  { name: "Port of Freeport", country: "Bahamas", lat: 26.53, lon: -78.7 },
  { name: "Port of Veracruz", country: "Mexico", lat: 19.2, lon: -96.13 },
  { name: "Port of Santos", country: "Brazil", lat: -23.96, lon: -46.33 },
  { name: "Port of Algeciras", country: "Spain", lat: 36.12, lon: -5.43 },
  { name: "Port of Valencia", country: "Spain", lat: 39.45, lon: -0.32 },
  { name: "Port of Piraeus", country: "Greece", lat: 37.94, lon: 23.64 },
  { name: "Jebel Ali Port", country: "United Arab Emirates", lat: 25.01, lon: 55.06 },
  { name: "Port Klang", country: "Malaysia", lat: 3.0, lon: 101.4 },
  { name: "Tanjung Pelepas", country: "Malaysia", lat: 1.36, lon: 103.55 },
  { name: "Laem Chabang", country: "Thailand", lat: 13.08, lon: 100.88 },
  { name: "Cai Mep (Vung Tau)", country: "Vietnam", lat: 10.52, lon: 107.05 },
  { name: "Nhava Sheva", country: "India", lat: 18.95, lon: 72.95 },
  { name: "Mundra Port", country: "India", lat: 22.74, lon: 69.71 },
  { name: "Port of Colombo", country: "Sri Lanka", lat: 6.95, lon: 79.85 },
  { name: "Port of Durban", country: "South Africa", lat: -29.87, lon: 31.03 },
  { name: "Port of Mombasa", country: "Kenya", lat: -4.05, lon: 39.65 },
  { name: "Port of Felixstowe", country: "United Kingdom", lat: 51.95, lon: 1.3 },
  { name: "Port of Hamburg", country: "Germany", lat: 53.87, lon: 8.7 },
  { name: "Manzanillo International", country: "Panama", lat: 9.36, lon: -79.88 },
  { name: "Port of Kingston", country: "Jamaica", lat: 17.96, lon: -76.79 },
  { name: "Port of Cartagena", country: "Colombia", lat: 10.42, lon: -75.53 },
];
